// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file demo.proto (package org.demo.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file demo.proto.
 */
export const file_demo: GenFile = /*@__PURE__*/
  fileDesc("CgpkZW1vLnByb3RvEgtvcmcuZGVtby52MSI5Cg1EZW1vQ29udGFpbmVyEigKB29iamVjdHMYASADKAsyFy5vcmcuZGVtby52MS5EZW1vT2JqZWN0IoYBCgpEZW1vT2JqZWN0Eh8KBGluZm8YASABKAsyES5vcmcuZGVtby52MS5JbmZvEgwKBG5hbWUYAiABKAkSIQoEdHlwZRgDIAEoDjITLm9yZy5kZW1vLnYxLk15VHlwZRINCgVjb3VudBgEIAEoBRIXCg9sb25nX2ZpZWxkX25hbWUYBSABKAkiIAoESW5mbxIKCgJpZBgBIAEoCRIMCgR0aW1lGAIgASgEIkMKEkRvU29tZXRoaW5nUmVxdWVzdBItCgljb250YWluZXIYASABKAsyGi5vcmcuZGVtby52MS5EZW1vQ29udGFpbmVyIkQKE0RvU29tZXRoaW5nUmVzcG9uc2USLQoJY29udGFpbmVyGAEgASgLMhoub3JnLmRlbW8udjEuRGVtb0NvbnRhaW5lcipMCgZNeVR5cGUSFwoTTVlfVFlQRV9VTlNQRUNJRklFRBAAEhMKD01ZX1RZUEVfRU5BQkxFRBABEhQKEE1ZX1RZUEVfRElTQUJMRUQQAjJkCg5EZW1vQXBpU2VydmljZRJSCgtEb1NvbWV0aGluZxIfLm9yZy5kZW1vLnYxLkRvU29tZXRoaW5nUmVxdWVzdBogLm9yZy5kZW1vLnYxLkRvU29tZXRoaW5nUmVzcG9uc2UiAGIGcHJvdG8z");

/**
 * @generated from message org.demo.v1.DemoContainer
 */
export type DemoContainer = Message<"org.demo.v1.DemoContainer"> & {
  /**
   * @generated from field: repeated org.demo.v1.DemoObject objects = 1;
   */
  objects: DemoObject[];
};

/**
 * Describes the message org.demo.v1.DemoContainer.
 * Use `create(DemoContainerSchema)` to create a new message.
 */
export const DemoContainerSchema: GenMessage<DemoContainer> = /*@__PURE__*/
  messageDesc(file_demo, 0);

/**
 * @generated from message org.demo.v1.DemoObject
 */
export type DemoObject = Message<"org.demo.v1.DemoObject"> & {
  /**
   * @generated from field: org.demo.v1.Info info = 1;
   */
  info?: Info;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: org.demo.v1.MyType type = 3;
   */
  type: MyType;

  /**
   * @generated from field: int32 count = 4;
   */
  count: number;

  /**
   * @generated from field: string long_field_name = 5;
   */
  longFieldName: string;
};

/**
 * Describes the message org.demo.v1.DemoObject.
 * Use `create(DemoObjectSchema)` to create a new message.
 */
export const DemoObjectSchema: GenMessage<DemoObject> = /*@__PURE__*/
  messageDesc(file_demo, 1);

/**
 * @generated from message org.demo.v1.Info
 */
export type Info = Message<"org.demo.v1.Info"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: uint64 time = 2;
   */
  time: bigint;
};

/**
 * Describes the message org.demo.v1.Info.
 * Use `create(InfoSchema)` to create a new message.
 */
export const InfoSchema: GenMessage<Info> = /*@__PURE__*/
  messageDesc(file_demo, 2);

/**
 * @generated from message org.demo.v1.DoSomethingRequest
 */
export type DoSomethingRequest = Message<"org.demo.v1.DoSomethingRequest"> & {
  /**
   * @generated from field: org.demo.v1.DemoContainer container = 1;
   */
  container?: DemoContainer;
};

/**
 * Describes the message org.demo.v1.DoSomethingRequest.
 * Use `create(DoSomethingRequestSchema)` to create a new message.
 */
export const DoSomethingRequestSchema: GenMessage<DoSomethingRequest> = /*@__PURE__*/
  messageDesc(file_demo, 3);

/**
 * @generated from message org.demo.v1.DoSomethingResponse
 */
export type DoSomethingResponse = Message<"org.demo.v1.DoSomethingResponse"> & {
  /**
   * @generated from field: org.demo.v1.DemoContainer container = 1;
   */
  container?: DemoContainer;
};

/**
 * Describes the message org.demo.v1.DoSomethingResponse.
 * Use `create(DoSomethingResponseSchema)` to create a new message.
 */
export const DoSomethingResponseSchema: GenMessage<DoSomethingResponse> = /*@__PURE__*/
  messageDesc(file_demo, 4);

/**
 * @generated from enum org.demo.v1.MyType
 */
export enum MyType {
  /**
   * @generated from enum value: MY_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MY_TYPE_ENABLED = 1;
   */
  ENABLED = 1,

  /**
   * @generated from enum value: MY_TYPE_DISABLED = 2;
   */
  DISABLED = 2,
}

/**
 * Describes the enum org.demo.v1.MyType.
 */
export const MyTypeSchema: GenEnum<MyType> = /*@__PURE__*/
  enumDesc(file_demo, 0);

/**
 * @generated from service org.demo.v1.DemoApiService
 */
export const DemoApiService: GenService<{
  /**
   * @generated from rpc org.demo.v1.DemoApiService.DoSomething
   */
  doSomething: {
    methodKind: "unary";
    input: typeof DoSomethingRequestSchema;
    output: typeof DoSomethingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_demo, 0);

