syntax = "proto3";

package org.demo.v1;

message DemoContainer {
    repeated DemoObject objects = 1;
}

message DemoObject {
    Info info = 1;
    string name = 2;
    MyType type = 3;
    int32 count = 4;
    string long_field_name = 5;
}

message Info {
    string id = 1;
    uint64 time = 2;
}

enum MyType {
    MY_TYPE_UNSPECIFIED = 0;
    MY_TYPE_ENABLED = 1;
    MY_TYPE_DISABLED = 2;
}

service DemoApiService {
    rpc DoSomething(DoSomethingRequest) returns (DoSomethingResponse) {};
}

message DoSomethingRequest {
    DemoContainer container = 1;
}

message DoSomethingResponse {
    DemoContainer container = 1;
}
